spring.application.name=ngnix
spring.datasource.username=venkatvs
spring.datasource.password=venkatvs56
spring.datasource.url=jdbc:mysql://venkat.czwke0g4e5rn.ap-south-1.rds.amazonaws.com/restapi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
